name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Readme with Waka Metrics
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.waka_63b542de-09a6-487d-bd59-2e0de3271bca }}
          GH_TOKEN: ${{ secrets.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 }}
